name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Change this to your default branch if not "main"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Zola
        run: |
          curl -sL https://get.zola.rs | bash
          sudo mv zola /usr/local/bin

      - name: Build the site
        run: zola build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
